### ISSUE TITLE
getting constant attributes

### ISSUE THREAD

**Issue by thipages** [WebReflection/heresy#19]
The example shows that the 2 first Test2 are displaying something, the third cant, everything ok

However I would like that the third behaves the same (easier to write...) displaying 100
How can I catch "a" in the thrid Test2 ?

```javascript
export const Test2 = {
    extends: 'div',
    mappedAttributes:['a'],
    ona() {this.render()},
    render(){
        this.html `Test2 : ${this.a}`
    }
};
heresy.define("Test2",Test2);
let a=1;
setInterval(()=> {
    a++;
    render (document.body,html`
        <Test2 .a=${a}/>
        <Test2 .a=${"10"}/>
        <Test2  a="100"/>
    `);
},1000);
```

**Comment by WebReflection** [comment]
The difference between `mappedAttributes` and `observedAttributes`, is that `mappedAttributes` uses simply a getter/setter, so that you never need to convert strings, but you can also pass along complex objects, callbacks, whatever, without ever reflecting these on the document, as these are meant to be consumed in JS.

The `observedAttributes` case, on the other hand, is the default Custom Element behavior, where you'll receive a change notification as string, as that's always the case for regular HTML attributes.

Accordingly, you could use `observedAttributes`, but you'd be responsible to cast strings into numbers.

```js
export const Test2 = {
    extends: 'div',
    observedAttributes:['a'],
    oninit() { this._a = 0; },
    onattributechanged({attributeName, newValue}) {
      this['_' + attributeName] = parseFloat(newValue);
      this.render();
    },
    render(){
        this.html `Test2 : ${this._a}`
    }
};
```

**Comment by thipages** [comment]
The corresponding code works. Thanks
Need to pay attention that "constant attribute" need no dot prefix


```javascript
export const Test2 = {
    extends: 'div',
    observedAttributes:['a'],
    mappedAttributes:['a'],
    ona() {
        this._a=this.a;
        this.render();
    },
    render(){
        this.html `Test2 : ${this._a}`
    },
    onattributechanged({attributeName, newValue}) {
        this['_' + attributeName] = parseFloat(newValue);
        this.render();
    },
};
heresy.define("Test2",Test2);

let a=1;
setInterval(()=> {
    a++;
    render (document.body,html`
        <Test2  .a=${a}/>
        <Test2  .a=${"10"}/>
        <Test2   a="100"/> <!-- with dot, no 100 display-->
    `);
},1000);
```

**Comment by WebReflection** [comment]
if I were you, as you pass a string in the second case, I'd use:
```js
    ona({detail}) {
        this.onattributechanged({attributeName: 'a', newValue: detail});
    },
```

so you have a centralized place to catch them all. However, it's your duty to document your component, and specify between attributes `a=${...}` and accessors `.a=${...}` so I would personally stick with attributes only.
