### ISSUE TITLE
Class vs Object notation component definition

### ISSUE THREAD

**Issue by hudelgado** [WebReflection/heresy#8]
Hi I'm having a problem when trying to define some abstract behavior and using it in the component definition.

In the following [example](https://codepen.io/hudelgado/pen/voZEez?editors=0012) there are two different component definitions, the first one with the Class works ok, on the second one with the Object is failing, because the component doesn't have a `what` method defined.

I can achieve the desired behavior using the Class definitions, but i can't find a way using the object notation.
How can achieve the same behavior using the object notation? 

Thanks

**Comment by hudelgado** [comment]
I have figured out what is happening and it isn't a problem, it is the way the heresy api works.

I also haven't noticed the heresy docs where it says that only accepts a raw object, i think it was referring to this.
The problem comes from the custom elements specification where it only allows to create them from classes, so the api only allows to receive a raw object as a component definition, and it will grab all the properties and symbols found directly in the given raw object.

Since by creating an element from a Class definition or from an raw object can give different scenarios, does the api should handle this specific scenario of the raw object definition and account for it in the same way as a Class definition? That is, does it make sense to recreate the object prototype chain in a similar way that is done now for the directly defined object properties but for the complete object prototype chain?

Now that i'm aware of this limitation i'm okay with it, but i will leave this ticket open so it can be discussed.

Thanks

**Comment by WebReflection** [comment]
I've admittedly not considered mixins when it comes to object literal definition, and the reason is that I'd personally go like this:

```js
let Dog = Object.assign(AnimalObjectMixin, {
  extends: 'element',
  oninit () {
    AnimalObjectMixin.oninit.call(this);
    this.what && this.what();
    console.log('Dog:init');
  }
});
```

In the literal case, this makes more sense to me, but I see where you're coming from in your example.

The issue is that crawling the prototype to create a chain of classes might not be as simple/straight forward as it looks like, so I need to think about a possible implementation that won't make literal usage a performance killer.

It's true that finding objects that don't directly inherit from `Object.prototype` and handle these separately shouldn't be a big issue, but doing this per each nested component might complicate the logic quite a bit.

__TL;DR__ once I'll be back from vacations I'll try to figure out a way to support your use case, but in the meanwhile I strongly suggest to use `Object.assign` which composes literals in a more natural way.

**Comment by hudelgado** [comment]
Ok, and thanks for the suggestion, it fits my needs i just wasn't aware this behavior.

There is no worries, if you feel it may make sense it can be implemented.

Have a nice vacations.
Cheers

**Comment by WebReflection** [comment]
I've been thinking about it, and decided to keep it simple as is with `Object.assign`, for at least these reasons:

  * object literals and `super` access looks kinda weird as a pattern
  * there is a performance impact in doing the prototype crawling per each possible nested/private object/class

Accordingly, if you need classes and prototypal inheritance just use classes, but if you need mixins with objects, just use `assign` or `Object.defineProperties(proto, Object.getOwnPropertyDescriptors(parent))` to preserve getters and setters.

I might re-think this in the future, but right now I don't see advantages in reducing performance for a use case that can be easily solved in other ways (i.e. `Object.assign({}, parent1, parent2)`)

Apologies if this is not the outcome you were expecting, and thanks for your understanding.
